### PR TITLE
Suport `derick init` to deteck the code type

### PR DESCRIPTION
**Pull request by zzxwill**
Based on all built-in riggings, python/golang/nodejs/...,
detect the code type of a project.

### CODE REVIEW

**Comment by zzxwill** [comment]
```
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/cloud-native-application/derrick-go git:(master) ✗ derrick-go

8888888b.                       d8b        888
888  "Y88b                      Y8P        888
888    888                                 888
888    888 .d88b. 888d888888d888888 .d8888b888  888
888    888d8P  Y8b888P"  888P"  888d88P"   888 .88P
888    88888888888888    888    888888     888888K
888  .d88PY8b.    888    888    888Y88b.   888 "88b
8888888P"  "Y8888 888    888    888 "Y8888P888  888

===================================================
Derrick is a scaffold tool to migrate applications
You can use Derrick to migrate your project simply.
===================================================
🐳 A tool to help you containerize application in seconds

Usage:
  derrick-go [command]

Available Commands:
  help        Help about any command
  init        Detect application's platform and compile the application
  version     Prints out build version information

Flags:
  -h, --help   help for derrick-go

Use "derrick-go [command] --help" for more information about a command.
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/cloud-native-application/derrick-go git:(master) ✗ derrick-go init -p /Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/try-cloudnative/try-derrick/derrick-nodejs-demo
Derrick detect your platform is NodeJS and compile it successfully.
```

**Comment by hongchaodeng** [comment]
Please don't create a new repo.
Just create a branch in https://github.com/alibaba/derrick and push there.

**Comment by zzxwill** [comment]
> Please don't create a new repo.
> Just create a branch in https://github.com/alibaba/derrick and push there.

@hongchaodeng
How about creating `https://github.com/alibaba/derrick-go`?
One the one hand, users can easily import the project in their go project, one the other hand, it will easily ruin the master Python project is the PR is mistakenly submitted to master branch.

**Comment by hongchaodeng** [comment]
> How about creating https://github.com/alibaba/derrick-go?

We don't have access to that org.

> One the one hand, users can easily import the project in their go project

The go code will take over the project in master branch and publish future releases.

> it will easily ruin the master Python project is the PR is mistakenly submitted to master branch.

We will set up branch protection.

**Comment by zzxwill** [comment]
@hongchaodeng No problem. Thanks.

**Pull request merged**
